-- 事前準備
-- 1.データベース演習と同様にサービスからMySQLを起動させる
-- 2.mysql -u root -pで管理者として入る

-- 1. データベース（箱）を作る
CREATE DATABASE safety_system_db CHARACTER SET utf8mb4;

-- 2. 作ったデータベースの中に入る（これ以降の操作対象にする）
USE safety_system_db;

-- 外部キー制約があるので作る順番が大事

-- 役職一覧マスタテーブル
CREATE TABLE E_POSITION (
    POSITION_NO  INT PRIMARY KEY,
    PNAME        VARCHAR(30) NOT NULL UNIQUE 

);

-- 部署一覧マスタテーブル
CREATE TABLE SECTION (
    SECTION_NO       INT PRIMARY KEY ,
    SNAME        VARCHAR(30) NOT NULL UNIQUE 

);

-- 社員一覧テーブル
-- CREATE TABLE EMPLOYEE (
--     EMP_NO       CHAR(5) PRIMARY KEY , 
--     PASSWORD     VARCHAR(255) NOT NULL  , -- 管理者が登録する(この時ハッシュ化) 
--     ENAME        VARCHAR(20) NOT NULL, 
--     BIRTHDAY     DATE NOT NULL, 
--     TEL          VARCHAR(15) NOT NULL UNIQUE,  
--     ADDRESS      VARCHAR(100) NOT NULL ,
--     E_POSITION     INT NOT NULL ,
--     SECTION      INT NOT NULL,
--     image_path   VARCHAR(255) ,
--     IS_DELETED   TINYINT DEFAULT 0 ,-- 論理削除用
--     FOREIGN KEY (E_POSITION) REFERENCES E_POSITION(POSITION_NO),
--     FOREIGN KEY (SECTION) REFERENCES SECTION(SECTION_NO) 
-- );
 CREATE TABLE EMPLOYEE (
          EMP_NO       CHAR(5) PRIMARY KEY , 
          PASSWORD     VARCHAR(255) NOT NULL  ,  
          ENAME        VARCHAR(20) NOT NULL, 
          BIRTHDAY     DATE NOT NULL, 
          TEL          VARCHAR(15) NOT NULL UNIQUE,  
          ADDRESS      VARCHAR(100) NOT NULL ,
          E_POSITION     INT NOT NULL ,
          SECTION      INT NOT NULL,
          image_path   VARCHAR(255) ,
          IS_DELETED   TINYINT DEFAULT 0 ,
          FOREIGN KEY (E_POSITION) REFERENCES E_POSITION(POSITION_NO),
          FOREIGN KEY (SECTION) REFERENCES SECTION(SECTION_NO) 
      );

-- 安否投稿トランザクションテーブル
-- CREATE TABLE SAFETY (
--     SAFE_NO      CHAR(5) PRIMARY KEY ,
--     SAFETY       INT     NOT NULL , --SAFE or DANGER処理
--     SAFE_TEXT    VARCHAR(200) ,
--     UPDATED_AT   DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP , -- 更新日時用
--     FOREIGN KEY (SAFE_NO) REFERENCES EMPLOYEE(EMP_NO)  -- 安否投稿は必ず社員番号と同じ番号でなければ出来ない

-- );
CREATE TABLE SAFETY (
          SAFE_NO      CHAR(5) PRIMARY KEY ,
          SAFETY       INT     NOT NULL , 
      SAFE_TEXT    VARCHAR(200) ,
      UPDATED_AT   DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP , 
      FOREIGN KEY (SAFE_NO) REFERENCES EMPLOYEE(EMP_NO)
      );


-- 役職一覧
INSERT INTO E_POSITION (POSITION_NO, PNAME)
VALUES(1, '社長');
INSERT INTO E_POSITION (POSITION_NO, PNAME)
VALUES(2, '部長');
INSERT INTO E_POSITION (POSITION_NO, PNAME)
VALUES(3, '課長');
INSERT INTO E_POSITION (POSITION_NO, PNAME)
VALUES(4, '係長');
INSERT INTO E_POSITION (POSITION_NO, PNAME)
VALUES(5, '一般社員');


-- 部署一覧
INSERT INTO SECTION (SECTION_NO, SNAME)
VALUES(1, 'システム管理部');
INSERT INTO SECTION (SECTION_NO, SNAME)
VALUES(2, '営業部');
INSERT INTO SECTION (SECTION_NO, SNAME)
VALUES(3, '企画部');
INSERT INTO SECTION (SECTION_NO, SNAME)
VALUES(4, '経理部');
INSERT INTO SECTION (SECTION_NO, SNAME)
VALUES(5, 'マーケティング部');
INSERT INTO SECTION (SECTION_NO, SNAME)
VALUES(6, '総務部');
INSERT INTO SECTION (SECTION_NO, SNAME)
VALUES(7, '役員');

-- テストデータ 
INSERT INTO EMPLOYEE(EMP_NO, PASSWORD, ENAME, BIRTHDAY, TEL, ADDRESS, E_POSITION, SECTION, image_path, IS_DELETED)
VALUES('00001', 'f2ca1bb6c7e907d06dafe4687e579fce76b37e4e93b7605022da52e6ccc26fd2', 'TEST管理部','2000-01-01','070-0001-0001','東京都千代田区千代田1-1',2,1,'KARI.JPG',0  );

INSERT INTO EMPLOYEE(EMP_NO, PASSWORD, ENAME, BIRTHDAY, TEL, ADDRESS, E_POSITION, SECTION, image_path, IS_DELETED)
VALUES('00002', 'f2ca1bb6c7e907d06dafe4687e579fce76b37e4e93b7605022da52e6ccc26fd2', 'TEST社員2','2000-01-02','070-0002-0002','東京都千代田区千代田1-1',5,2,'KARI.JPG',0  );

INSERT INTO EMPLOYEE(EMP_NO, PASSWORD, ENAME, BIRTHDAY, TEL, ADDRESS, E_POSITION, SECTION, image_path, IS_DELETED)
VALUES('00003', 'f2ca1bb6c7e907d06dafe4687e579fce76b37e4e93b7605022da52e6ccc26fd2', 'TEST社員3','2000-01-03','070-0003-0003','東京都千代田区千代田1-1',5,2,'KARI.JPG',0  );

INSERT INTO EMPLOYEE(EMP_NO, PASSWORD, ENAME, BIRTHDAY, TEL, ADDRESS, E_POSITION, SECTION, image_path, IS_DELETED)
VALUES('00004', 'f2ca1bb6c7e907d06dafe4687e579fce76b37e4e93b7605022da52e6ccc26fd2', '退職社員1','2000-01-03','070-0004-0004','東京都千代田区千代田1-1',5,2,'KARI.JPG',1  ); 
-- 退職社員ログイン実験用