CREATE TABLE EMPLOYEE (
    EMP_NO       CHAR(5) PRIMARY KEY AUTOINCREMENT, 
    PASSWORD     VARCHAR(255) NOT NULL  , 
    ENAME        VARCHAR(20) NOT NULL, 
    BIRTHDAY     DATE NOT NULL, 
    TEL          VARCHAR(15) NOT NULL UNIQUE,  
    ADDRESS      VARCHAR(100) NOT NULL ,
    POSITION     INT NOT NULL ,
    SECTION      INT NOT NULL,
    image_path   VARCHAR(255) ,
    IS_DELETED   TINYINT DEFAULT 0 -- 論理削除用

);

CREATE TABLE SAFETY (
    SAFE_NO      CHAR(5) PRIMARY KEY ,
    SAFETY       CHAR(1) NOT NULL ,
    SAFE_TEXT    VARCHAR(200) ,
    UPDATED_AT   DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP , -- 更新日時用
    FOREIGN KEY (SAFE_NO) REFERENCES EMPLOYEE(EMP_NO)  -- 安否投稿は必ず社員番号と同じ番号でなければ出来ない

);

CREATE TABLE POSITION (
    POSITION_NO  INT PRIMARY KEY,
    PNAME        VARCHAR(30) NOT NULL UNIQUE ,

);

CREATE TABLE SECTION (
    JOB_NO       INT PRIMARY KEY ,
    JNAME        VARCHAR(30) NOT NULL UNIQUE ,

);

